import { DISK_UTILIZATION_FIELDS } from './DISK_UTILIZATION_FIELDS';

export const MULTIPLE_DEVICE_UTILIZATION = 'MDD';

export const MULTIPLE_DEVICE_UTILIZATION_FIELDS = [...DISK_UTILIZATION_FIELDS];
